# Generated by Django 3.2.4 on 2021-10-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(default='Poland', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='postal_code',
            field=models.CharField(default='00-000', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
